import os
import json
from pathlib import Path

dados = pd.read_json('H:/teste.json', orient='records')
#print(dados)
dados.to_csv('H:/teste.csv')

#file must be with a json format accepted by Pandas, in my case had to erase part of specieslink file for it to start with "[" and end with "]"
#must not have any windows lines, each record must be in one line between {} , as to be readed each record. Example json comented below

#[{"collectioncode":"DZUP-PLECOPTERA","maximumelevation":"300","datelastmodified":"2017-03-03T09:55:16","verbatimlatitude":"-27,1833","daycollected":"01","minimumelevation":"300","monthcollected":"11","latitude":"-27.1833","country":"Brasil","longitude":"-52.3833","collector":"Fritz Plaumann","verbatimlongitude":"-52,3833","genus":"Anacroneuria","kingdom":"Animalia","basisofrecord":"PreservedSpecimen","scientificname":"Anacroneuria","yearcollected":"1980","catalognumber":"287220","stateprovince":"Santa Catarina","notes":"<nO>Altitude de 300-500 metros</nO>","phylum":"Arthropoda","county":"Nova Teutônia","family":"Perlidae","institutioncode":"UFPR"},
#{"collectioncode":"DZUP-PLECOPTERA","maximumelevation":"300","datelastmodified":"2017-03-03T09:55:16","verbatimlatitude":"-27,1833","daycollected":"01","minimumelevation":"300","monthcollected":"11","latitude":"-27.1833","country":"Brasil","longitude":"-52.3833","collector":"Fritz Plaumann","verbatimlongitude":"-52,3833","genus":"Anacroneuria","kingdom":"Animalia","basisofrecord":"PreservedSpecimen","scientificname":"Anacroneuria","yearcollected":"1980","catalognumber":"287221","stateprovince":"Santa Catarina","notes":"<nO>Altitude de 300-500 metros</nO>","phylum":"Arthropoda","county":"Nova Teutônia","family":"Perlidae","institutioncode":"UFPR"},
#{"collectioncode":"DZUP-PLECOPTERA","maximumelevation":"300","datelastmodified":"2017-03-03T09:55:16","verbatimlatitude":"-27,1833","daycollected":"01","minimumelevation":"300","monthcollected":"11","latitude":"-27.1833","country":"Brasil","longitude":"-52.3833","collector":"Fritz Plaumann","verbatimlongitude":"-52,3833","genus":"Anacroneuria","kingdom":"Animalia","basisofrecord":"PreservedSpecimen","scientificname":"Anacroneuria","yearcollected":"1980","catalognumber":"287222","stateprovince":"Santa Catarina","notes":"<nO>Altitude de 300-500 metros</nO>","phylum":"Arthropoda","county":"Nova Teutônia","family":"Perlidae","institutioncode":"UFPR"},
#{"collectioncode":"RECOLNAT_MNHN_IC","scientificnameauthor":"(cuvier, 1830)","datelastmodified":"2016-09-30T11:07:51","individualcount":"1","verbatimlatitude":"-23","latitude":"-23","country":"Brasil","longitude":"-43.283","collector":"jobert","verbatimlongitude":"-43.283","kingdom":"Animalia","genus":"Orthopristis","barcode":"ICA-2707","basisofrecord":"PreservedSpecimen","species":"ruber","scientificname":"Orthopristis ruber","yearcollected":"1876","catalognumber":"A-2707","stateprovince":"Rio de Janeiro","notes":"<nO><a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/a-2707' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Haemulidae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","scientificnameauthor":"(bloch, 1797)","datelastmodified":"2016-09-30T11:07:51","individualcount":"2","verbatimlatitude":"-12.967","latitude":"-12.967","country":"Brasil","longitude":"-38.483","collector":"brunet","verbatimlongitude":"-38.483","kingdom":"Animalia","genus":"Prionotus","barcode":"ICA-0285","basisofrecord":"PreservedSpecimen","species":"punctatus","scientificname":"Prionotus punctatus","yearcollected":"1876","catalognumber":"A-0285","stateprovince":"Bahia","notes":"<nO><a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/a-0285' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Triglidae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","identifiedby":"wheeler","scientificnameauthor":"(linnaeus, 1766)","datelastmodified":"2016-09-30T11:07:51","individualcount":"1","verbatimlatitude":"-12.967","latitude":"-12.967","country":"Brasil","longitude":"-38.483","collector":"brunet","verbatimlongitude":"-38.483","kingdom":"Animalia","genus":"Opsanus","barcode":"ICA-4541","basisofrecord":"PreservedSpecimen","species":"tau","scientificname":"Opsanus tau","yearcollected":"1876","catalognumber":"A-4541","stateprovince":"Bahia","notes":"<nO><a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/a-4541' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Batrachoididae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","identifiedby":"greenfield et johnson","scientificnameauthor":"(quoy & gaimard, 1824)","datelastmodified":"2016-09-30T11:07:51","individualcount":"1","verbatimlatitude":"-23","latitude":"-23","country":"Brasil","longitude":"-43.283","collector":"gay","verbatimlongitude":"-43.283","kingdom":"Animalia","genus":"Labrisomus","barcode":"ICA-3451","species":"nuchipinnis","basisofrecord":"PreservedSpecimen","scientificname":"Labrisomus nuchipinnis","catalognumber":"A-3451","stateprovince":"Rio de Janeiro","notes":"<nO>SYNTYPE DE CLINUS PECTINIFER VALENCIENNES, 1836 IN C.V., H.N.P., XI : 374 / VOIR FIELDIANA ZOOL., N.S., N° 8 : 23 <a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/a-3451' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Labrisomidae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","scientificnameauthor":"(cuvier, 1829)","datelastmodified":"2016-09-30T11:07:51","individualcount":"1","verbatimlatitude":"-12.967","latitude":"-12.967","country":"Brasil","longitude":"-38.483","collector":"inconnu|geneve mhng, m.","verbatimlongitude":"-38.483","kingdom":"Animalia","genus":"Diapterus","barcode":"ICA-2236","species":"rhombeus","basisofrecord":"PreservedSpecimen","scientificname":"Diapterus rhombeus","catalognumber":"A-2236","stateprovince":"Bahia","notes":"<nO><a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/a-2236' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Gerreidae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","identifiedby":"greenfield et greenfield","scientificnameauthor":"(valenciennes, 1837)","datelastmodified":"2016-09-30T11:07:51","individualcount":"1","verbatimlatitude":"-12.967","latitude":"-12.967","country":"Brasil","longitude":"-38.483","collector":"blanchet|geneve mhng, m.","verbatimlongitude":"-38.483","kingdom":"Animalia","genus":"Amphichthys","barcode":"ICA-4784","species":"cryptocentrus","basisofrecord":"PreservedSpecimen","scientificname":"Amphichthys cryptocentrus","catalognumber":"A-4784","stateprovince":"Bahia","notes":"<nO>SYNTYPE DE BATRACHUS CRYPTOCENTRUS VALENCIENNES, 1837 IN C.V., H.N.P., XII : 485 <a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/a-4784' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Batrachoididae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","scientificnameauthor":"(linnaeus, 1766)","datelastmodified":"2016-09-30T11:07:51","individualcount":"1","verbatimlatitude":"-12.967","latitude":"-12.967","country":"Brasil","longitude":"-38.483","collector":"blanchet|geneve mhng, m.","verbatimlongitude":"-38.483","kingdom":"Animalia","genus":"Synodus","barcode":"ICB-0977","basisofrecord":"PreservedSpecimen","species":"foetens","scientificname":"Synodus foetens","yearcollected":"1833","catalognumber":"B-0977","stateprovince":"Bahia","notes":"<nO>ETUDIES PAR VALENCIENNES, 1849 IN C.V., H.N.P., XXII : 471/ un spécimen extrait : 1998-573. <a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/b-0977' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Synodontidae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","scientificnameauthor":"(cuvier, 1830)","datelastmodified":"2016-09-30T11:07:51","individualcount":"1","verbatimlatitude":"-12.967","latitude":"-12.967","country":"Brasil","longitude":"-38.483","collector":"inconnu|geneve mhng, m.","verbatimlongitude":"-38.483","kingdom":"Animalia","genus":"Stegastes","barcode":"ICA-2546","species":"fuscus","basisofrecord":"PreservedSpecimen","scientificname":"Stegastes fuscus","catalognumber":"A-2546","stateprovince":"Bahia","notes":"<nO>EX EUPOMACENTRUS FUSCUS <a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/a-2546' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Pomacentridae","institutioncode":"MNHN"},
#{"collectioncode":"RECOLNAT_MNHN_IC","datelastmodified":"2016-09-30T11:07:52","scientificnameauthor":"cardoso & malabarba, 1999","individualcount":"2","verbatimlatitude":"-29.263","daycollected":"13","monthcollected":"7","latitude":"-29.263","country":"Brasil","collector":"reis|pezzi|bertaco","longitude":"-53.234","verbatimlongitude":"-53.234","genus":"Hemiancistrus","kingdom":"Animalia","species":"punctulatus","basisofrecord":"PreservedSpecimen","barcode":"IC2004-1621","scientificname":"Hemiancistrus punctulatus","yearcollected":"1999","catalognumber":"2004-1621","stateprovince":"rio grande du sud","notes":"<nO><a href='http://coldb.mnhn.fr/catalognumber/mnhn/ic/2004-1621' target='other'> <mi>dwc_moreinfo</mi></a></nO>","phylum":"Chordata","family":"Loricariidae","institutioncode":"MNHN"}]
